backend:
  name: git-gateway
  branch: master
  squash_merges: true
  commit_messages:
    create: "feat: create {{collection}} '{{slug}}' by NetlifyCMS "
    update: "feat: update {{collection}} '{{slug}}' by NetlifyCMS "
    delete: "feat: delete {{collection}} '{{slug}}' by NetlifyCMS "
    uploadMedia: "feat: upload '{{path}}' by NetlifyCMS "
    deleteMedia: "feat: delete '{{path}}' by NetlifyCMS "

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/md-pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Post URL", name: "path", widget: "postUrl", prefix: "/blog/", selector: "[id^='title']"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}